### ISSUE TITLE
add testing tools

### ISSUE THREAD

**Issue by skibinska** [skibinska/personal-website#6]
- [x]  TravisCI

- [x] Code Climate

- [x] Codecov

- [x] Istanbul

**Comment by skibinska** [comment]
Finally I figured out how to make code climate to work.

add to .travis.yml
```
addons:
    code_climate:
        repo_token: TOKEN
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
```
